### ISSUE TITLE
meet an error!

### ISSUE THREAD

**Issue by Rurouni-z** [oceam/LeafSurfaceReconstruction#1]
Leafs path: ['11_20190508T043118_pot1_1.txt', '11_20190508T043118_pot1_15.txt', '11_20190508T043118_pot1_17.txt', '11_20190508T043118_pot1_36.txt']
Output folder: output/soybean
skipped: /home/ubuntu/3D_MODEL/LeafSurfaceReconstruction/output/soybean/11_20190508T043118_pot1_1
Component 1 has been reversed.
angle: 0
angle: 60
angle: 120
h axis is not pointing leaf top. Reverse it.
0.32383917314819205
0.3669365557958191
result 1: (3284, 3)
result 2: (3190, 3)
11_20190508T043118_pot1_1.txt: Done
Component 1 has been reversed.
Component 3 has been reversed.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 1531 requests (1531 known processed) with 7 events remaining.
      after 1531 requests (1531 known processed) with 9 events remaining.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 1531 requests (1531 known processed) with 7 events remaining.
XIO:  fatal IO error 0 (Success) on X server ":1"
      after 1535 requests (1535 known processed) with 7 events remaining.
Traceback (most recent call last):
  File "/home/ubuntu/3D_MODEL/LeafSurfaceReconstruction/reconstruction.py", line 73, in <module>
    result1, result2 = reconstruct(path_params)
  File "/home/ubuntu/3D_MODEL/LeafSurfaceReconstruction/reconstruction.py", line 45, in reconstruct
    one_way, two_way = leafProcess.reconstruction()
  File "/home/ubuntu/3D_MODEL/LeafSurfaceReconstruction/utils/leaf_process.py", line 46, in reconstruction
    w_axis, l_axis, h_axis = leafAxisDetermination.process()
  File "/home/ubuntu/3D_MODEL/LeafSurfaceReconstruction/utils/leaf_axis_determination.py", line 118, in process
    self.surface_area_list.append(future.result()[0])
  File "/home/ubuntu/anaconda3/envs/soft/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/ubuntu/anaconda3/envs/soft/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by Rurouni-z** [comment]
soved by set [max_workers](https://github.com/oceam/LeafSurfaceReconstruction/blob/master/utils/leaf_axis_determination.py#L113)=1

**Comment by Rurouni-z** [comment]
XIO:  fatal IO error 25 (Inappropriate ioctl for device) on X server ":1"
      after 1531 requests (1531 known processed) with 7 events remaining.

... i think wrong

**Comment by Rurouni-z** [comment]
i changed 5 and 6 to :
```python
res = []    
for i in range(180):
    r = surface_area_calculation(l_axis, d_axis, bins, bin_range, self.p_init, i)
    res.append(r)
for future in res:
    self.surface_area_list.append(future[0])

```
except **not using parallelism**
